# Generated by Django 4.2.29 on 2026-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('frame_type', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('race', models.CharField(max_length=100)),
                ('archetype', models.CharField(blank=True, default='', max_length=100)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('def_points', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('attribute', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=200)),
                ('set_code', models.CharField(max_length=50)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_price', models.CharField(max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='yugi_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcgplayer_price', models.CharField(max_length=20)),
                ('ebay_price', models.CharField(max_length=20)),
                ('amazon_price', models.CharField(max_length=20)),
                ('cardmarket_price', models.CharField(max_length=20)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='yugi_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_small', models.URLField()),
                ('image_cropped', models.URLField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yugi_app.card')),
            ],
        ),
    ]
